src/Entity/Horaires.php
<?php

namespace App\Entity;

use App\Repository\HorairesRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: HorairesRepository::class)]
class Horaires
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $heure_matin = null;

    #[ORM\Column(length: 255)]
    private ?string $heure_soir = null;

    #[ORM\Column(length: 255)]
    private ?string $jour = null;

    #[ORM\ManyToOne(inversedBy: 'horaires')]
    private ?Users $parent = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getHeureMatin(): ?string
    {
        return $this->heure_matin;
    }

    public function setHeureMatin(string $heure_matin): static
    {
        $this->heure_matin = $heure_matin;

        return $this;
    }

    public function getHeureSoir(): ?string
    {
        return $this->heure_soir;
    }

    public function setHeureSoir(string $heure_soir): static
    {
        $this->heure_soir = $heure_soir;

        return $this;
    }

    public function getJour(): ?string
    {
        return $this->jour;
    }

    public function setJour(string $jour): static
    {
        $this->jour = $jour;

        return $this;
    }

    public function getParent(): ?Users
    {
        return $this->parent;
    }

    public function setParent(?Users $parent): static
    {
        $this->parent = $parent;

        return $this;
    }
}

templates/_partials/_flash.html.twig
{% for label, messages in app.flashes %}
    {% for message in messages %}
        <div class="alert alert-{{label}} alert-dismissible" role="alert">
            <button type="button" class=" btn-close" data-bs-dismiss="alert" aria-label="close"></button>
            <div class="alert-message">
                {{message|raw}}
            </div>
        </div>
    {% endfor %}
    
{% endfor %}
{# ce bout de code permet d'afficher tous les messages d'alertes quel qu'ils soient dans toutes les pages  #}

templates/_partials/_footer.html.twig
<footer>
        <div class="bg-blk footer">
        <div class="clock">
            {% for horaire in horaires %}
                <p>{{ horaire.heureMatin }}</p>
                <p>{{ horaire.heureSoir }}</p>
                <p>{{ horaire.jour }}</p>
            {% endfor %}
            <a data-bs-toggle="modal" data-bs-target="#exampleModal1" style="text-decoration: underline; text-underline-offset: 5px; cursor: pointer; color: #fdba3d" class="d-flex justify-content-center">
            Mentions légales</a>

            <div class="modal fade" id="exampleModal1" tabindex="-1" aria-labelledby="exampleModalLabel1" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel1">Mentions légales</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <h6>éditeur du site</h6>
        <p style="color: black;">nom du propriétaire : ballesteros romain <br>
        adresse : 40 chemin du clos dou fan 30190 castelnau valence <br>
        téléphone : 06.86.11.60.16 <br>
        mail : romain.ballesteros@gmail.com</p>
        <h6>hébergeur du site</h6>
        <p style="color: black;"> hébergeur : heroku.com</p>
        <h6>propriété intellectuelle</h6>
        <p style="color: black;">Le contenu de ce site (textes, images, vidéos, etc.) est protégé par les droits de propriété intellectuelle. Toute reproduction ou utilisation sans autorisation préalable est interdite.</p>
        <h6>données personelles</h6>
        <p style="color: black;">Conformément à la loi Informatique et Libertés du 6 janvier 1978, vous disposez d'un droit d'accès, de rectification et de suppression des données vous concernant. Pour exercer ce droit, veuillez nous contacter par e-mail à l'adresse suivante : romain.ballesteros@gmail.com</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn2" data-bs-dismiss="modal">Close</button>

      </div>
    </div>
  </div>
</div>
        </div>
        
            <div class="trait2"></div>
            <img src="{{asset('assets/images/Garage_V.parrot.png')}}" alt="logo">
        <div class="clock">
            <p>contactez nous : <br>01 85 66 32 15 <br>contact@vparrot.fr <br>30 rue de la reussite <br>34000
                <br>montpellier
            </p>
            <!-- Button trigger modal -->
<a data-bs-toggle="modal" data-bs-target="#exampleModal" style="text-decoration: underline; text-underline-offset: 5px; cursor: pointer; color: #fdba3d" class="d-flex justify-content-center">
Politique des cookies
</a>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Politique des cookies</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <h6>utilisation</h6>
        <p style="color: black;">ce site utilise des cookies poour améliorer votre expérience utilisateur. ces cookies sont essentiels pour la gestion de vos droits et privilèges au sein de notre sysème.</p>
        <h6>les cookies qu'est ce que c'est  ?</h6>
        <p style="color: black;">un cookie est un petit fichier stocker sur votre ordinateur ou smartphone par le navigateur web que vous utilisez. ces fichiers nous aident à vous identifier en tant qu'utilisateur et à personnaliser votre expérience en fonction de vos préférences.</p>
        <h6>comment nous les utilisons ?</h6>
        <p style="color: black;">nous les utilisons uiquement pour la gestion de vos droit en tant qu'utilisateur. ils ne collectent pas d'informations personelles et ne sont pas utilisés à des fins de marketing ou de suivi.</p>
        <h6>votre consentement</h6>
        <p style="color: black;">en continuant à utiliser ce site, vous consentez à l'utilisation de ces cookies.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn2" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
        </div>
        </div>
    </footer>

templates/_partials/_mail.html.twig
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Identifiants de connexion</title>
</head>
<body>
    <h2> Monsieur parrot vous à créer un compte</h2>
    <p>Utilisez ces informations pour vous connecter sur le site du garage v.parrot</p>
    <p>Votre email : {{ mail }}</p>
    <p>Votre mmot de passe : {{ password }}</p>
    <strong> Votre mot de passe est confidentiel ne le donnez à personne</strong>
</body>
</html>

templates/_partials/_nav.html.twig
    <header class="header">
        <a href="{{path('home_')}}"><img class="logo" src="{{asset('assets/images/Garage_V.parrot.png')}}"
                alt="logo garage"></a>
        <div class="navi">
            <a href="{{path('app_login')}}"><button class="connexion">connexion</button></a>
            <nav class="Le_menu">
                <div class="toggle">
                    <img src="{{asset('assets/images/bars-solid.svg')}}" alt="menu button" class="ouvrir">
                    <img src="{{asset('assets/images/x-lg.svg')}}" alt="bouton fermer menu" class="fermer">
                </div>
                <ul class="menu">
                    <li><a href="{{path('home_')}}">Accueil</a></li>
                    <li><a href="{{path('app_carrosserie')}}">Carrosserie</a></li>
                    <li><a href="{{path('app_cars')}}"> Véhicules<br>d'occasion</a></li>
                    <li><a href="{{path('app_mecanique')}}">Mécanique</a></li>
                    <li><a href="{{path('app_formulaire')}}">Contacts</a></li>
                </ul>
            </nav>
        </div>
    </header>

templates/_partials/_pagination.html.twig
{#
/**
 * @file
 * Bootstrap v5 Sliding pagination control implementation.
 *
 * View that can be used with the pagination module
 * from the Bootstrap CSS Framework
 * https://getbootstrap.com/docs/5.0/components/pagination/
 */
#}
{% extends '@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig' %}